### ISSUE TITLE
No full pinout

### ISSUE THREAD

**Issue by ffnull** [CrealityOfficial/Sermoon-V1#2]
Hello. While analize pins_CREALITY_F401RE.h file there missing pinout for RGB led out and PWON pin. Please Fix
Its:
PA0-R
PA1-B
PA6-G

PB5-PWRON

**Comment by CrealityTech** [comment]
> Hello. While analize pins_CREALITY_F401RE.h file there missing pinout for RGB led out and PWON pin. Please Fix Its: PA0-R PA1-B PA6-G
> 
> PB5-PWRON

on creality motherboards not support RGB LED port;
we sorry for that
